In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("../data/results.csv")

In [6]:
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [8]:
df.isnull().sum()

date           0
home_team      0
away_team      0
home_score    72
away_score    72
tournament     0
city           0
country        0
neutral        0
dtype: int64

In [10]:
df = df.dropna(subset= ["home_score","away_score"])

In [12]:
df.isnull().sum()

date          0
home_team     0
away_team     0
home_score    0
away_score    0
tournament    0
city          0
country       0
neutral       0
dtype: int64

In [13]:
df["date"] = pd.to_datetime(df["date"])

In [14]:
df["year"] = df["date"].dt.year

In [15]:
df.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral', 'year'],
      dtype='str')

In [16]:
df["home_score"] = df["home_score"].astype(int)
df["away_score"] = df["away_score"].astype(int)

In [17]:
def get_result(row):
    if row["home_score"] > row["away_score"]:
        return "home_win"
    elif row["home_score"] < row["away_score"]:
        return "away_win"
    return "draw"

df["result"] = df.apply(get_result, axis=1)

In [18]:
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,result
0,1872-11-30,Scotland,England,0,0,Friendly,Glasgow,Scotland,False,1872,draw
1,1873-03-08,England,Scotland,4,2,Friendly,London,England,False,1873,home_win
2,1874-03-07,Scotland,England,2,1,Friendly,Glasgow,Scotland,False,1874,home_win
3,1875-03-06,England,Scotland,2,2,Friendly,London,England,False,1875,draw
4,1876-03-04,Scotland,England,3,0,Friendly,Glasgow,Scotland,False,1876,home_win

In [19]:
print(df["result"].value_counts())

result
home_win    24149
away_win    13928
draw        11204
Name: count, dtype: int64

In [21]:
df.to_csv("../data/cleaned_results.csv",index=False)

In [22]:
df.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,result
49276,2026-05-31,Poland,Ukraine,0,2,Friendly,Wrocław,Poland,False,2026,away_win
49277,2026-05-31,Singapore,Mongolia,4,0,Friendly,Singapore,Singapore,False,2026,home_win
49278,2026-05-31,Switzerland,Jordan,4,1,Friendly,St. Gallen,Switzerland,False,2026,home_win
49279,2026-05-31,United States,Senegal,3,2,Friendly,Charlotte,United States,False,2026,home_win
49280,2026-05-31,Japan,Iceland,1,0,Friendly,Tokyo,Japan,False,2026,home_win

In [31]:
df.shape

(49281, 11)

In [34]:
df = pd.read_csv("../data/cleaned_results.csv")

In [35]:
df.shape

(49281, 11)

In [40]:
df["result"].value_counts()

result
home_win    24149
away_win    13928
draw        11204
Name: count, dtype: int64

In [37]:
df["year"].min()

np.int64(1872)

In [38]:
df["year"].max()

np.int64(2026)

In [39]:
len(set(df["home_team"]).union(set(df["away_team"])))

336